### ISSUE TITLE
Unable to build on Alpine Linux 3.21, GCC 14.2.0

### ISSUE THREAD

**Issue by frenck** [animetosho/ParPar#64]
I wasn't able to build it (through par2cmdline-turbo) on Alpine Linux 3.21; musl, GCC 14.2.0

```
#6 129.1 In file included from parpar/hasher/md5-scalar.h:3,
#6 129.1                  from parpar/hasher/md5-final.c:2:
#6 129.1 parpar/hasher/md5-base.h: In function 'md5_alloc_scalar':
#6 129.1 parpar/hasher/../src/platform.h:303:49: error: implicit declaration of function 'posix_memalign'; did you mean '_mm_posix_memalign'? [-Wimplicit-function-declaration]
#6 129.1   303 |         #define ALIGN_ALLOC(buf, len, align) if(posix_memalign((void**)&(buf), align < sizeof(void*) ? sizeof(void*) : align, (len))) (buf) = NULL
#6 129.1       |                                                 ^~~~~~~~~~~~~~
#6 129.1 parpar/hasher/md5-base.h:315:9: note: in expansion of macro 'ALIGN_ALLOC'
#6 129.1   315 |         ALIGN_ALLOC(ret, sizeof(word_t)*words, sizeof(word_t) < sizeof(void*) ? sizeof(void*) : sizeof(word_t));
#6 129.1       |         ^~~~~~~~~~~
#6 129.1 make[1]: *** [Makefile:2684: parpar/hasher/libparpar_hasher_a-md5-final.o] Error 1
```

**Comment by animetosho** [comment]
If you're using the v1.1.1 release, could you try with the latest Git instead?

Might be duplicate of https://github.com/animetosho/par2cmdline-turbo/issues/34

**Comment by frenck** [comment]
Check, thanks! I've been searching, but didn't ran into that linked issue. Sorry for the noise 🙏 

I've tested against the latest main branch of the repo, and it is indeed able to build correctly now.

Thanks! 👍 

../Frenck
